### ISSUE TITLE
(Just a reminder) SSL Certificate Expired

### ISSUE THREAD

**Issue by bypass-city** [alxhotel/webtorrent-checker#77]
from mobile got inaccessible due to certificate expiration

**Comment by alxhotel** [comment]
Thanks, @bypass-city!

It's fixed now

**Comment by arseniov** [comment]
@alxhotel SSL certificate expired again 😟

**Comment by alxhotel** [comment]
Thanks, @arseniov !

I have now automated the SSL cert update. So it should never happen
